参考：
- https://github.com/datawhalechina/competition-baseline/blob/master/competition/%E7%A7%91%E5%A4%A7%E8%AE%AF%E9%A3%9EAI%E5%BC%80%E5%8F%91%E8%80%85%E5%A4%A7%E8%B5%9B2023/%E5%9F%BA%E4%BA%8E%E8%BF%91%E7%BA%A2%E5%A4%96%E5%85%89%E8%B0%B1%E7%9A%84%E7%85%A4%E8%B4%A8%E5%8F%82%E6%95%B0%E9%A2%84%E6%B5%8B%E6%8C%91%E6%88%98%E8%B5%9B_baseline.ipynb
- https://xueshu.baidu.com/usercenter/paper/show?paperid=3539e308bda4e1f9d223f029df8ce7a3

数据集获取：
https://www.datafountain.cn/datasets/6948

赛事链接：
https://www.datafountain.cn/competitions/669

In [1]:
import pandas as pd
train_data = pd.read_csv('data/train_data.csv')
train_label = pd.read_csv('data/train_label.csv')

test_data = pd.read_csv('data/test_data.csv')
# submit = pd.read_csv('提交示例.csv')

In [2]:
test_data.shape, train_data.shape

((100, 126), (500, 126))

In [3]:
train_label.head()

   样品编号    水分     灰分
0     0  12.2   6.04
1     1  11.7   6.03
2     2   9.0  29.58
3     3   7.6  22.95
4     4  14.4  19.87

In [4]:
train_data.head()

,样品编号,908.1,914.294,920.489,926.683,932.877,939.072,945.266,951.46,957.655,...,1620.451,1626.645,1632.839,1639.034,1645.228,1651.423,1657.617,1663.811,1670.006,1676.2
0,0,0.727191,0.743425,0.758716,0.773788,0.789644,0.801787,0.809344,0.814902,0.818428,...,0.626854,0.625457,0.624087,0.622978,0.621804,0.620750,0.619933,0.619106,0.618328,0.617689
1,1,0.739590,0.755127,0.769929,0.785550,0.800114,0.811810,0.819550,0.825737,0.828964,...,0.643333,0.641930,0.640543,0.639434,0.638211,0.637155,0.636376,0.635590,0.634830,0.634196
2,2,0.768334,0.788929,0.792230,0.800625,0.817170,0.825030,0.832188,0.828150,0.835385,...,0.697492,0.694766,0.690777,0.693793,0.689134,0.695828,0.693195,0.690598,0.690741,0.689176
3,3,0.778953,0.785754,0.799091,0.818461,0.814529,0.824412,0.834525,0.829672,0.829585,...,0.710395,0.705778,0.704238,0.703424,0.706041,0.697049,0.699936,0.699833,0.702512,0.700228
4,4,0.769661,0.784200,0.793263,0.802113,0.817382,0.819240,0.821661,0.821987,0.824198,...,0.699176,0.699278,0.695768,0.697422,0.704235,0.696586,0.693301,0.695314,0.691957,0.688685

In [5]:
submit = pd.DataFrame()

In [6]:
from sklearn.linear_model import LinearRegression

m = LinearRegression()
m.fit(train_data.iloc[:, 1:], train_label['水分'])
submit['水分'] = m.predict(test_data.iloc[:, 1:])

m = LinearRegression()
m.fit(train_data.iloc[:, 1:], train_label['灰分'])
submit['灰分'] = m.predict(test_data.iloc[:, 1:])

submit.to_csv('lr.csv', index=None)